# Script to grab all the individually saved dataset fits (generated by 'fit_all_datasets.R') from a specified directory and return them as a bundled list object for subsequent profiling and plotting

bundle_fits <- function(dir){
  fits <- list.files(dir, pattern='.Rdata',full.names=TRUE, include.dirs=FALSE)
  bundled_fits <- list()
  for (i in 1:length(fits)){
    load(fits[i]) # returns the 'ffr.fit' object
    bundled_fits[[i]] <- ffr.fit
  }
  return(bundled_fits)
}


# ffr.fits <- bundle_fits('../../../results/R/OnePredOnePrey_fits/')
